# Pequeña demo de despliegue en GitHub Pages, aprovechando su servicio gratuito
# Nombre del flujo de trabajo
name: DemoGitHubActions

on:
  # Se dispara el flujo de trabajo cuando se realiza un push o pull a la rama 
  push:
    branches: [ AutomatizacionGitHubActions ]
  pull_request:
    branches: [ AutomatizacionGitHubActions ]
  workflow_dispatch:

